version: '3'

networks:
  grafana:
  timescaledb:

services:
  timescaledb:
    container_name: timescaledb
    # doesn't include promscale
    # image: timescale/timescaledb:latest-pg14
    image: timescale/timescaledb-ha:pg14-latest
    restart: on-failure
    ports:
      - 5432:5432/tcp
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: localhost
      POSTGRES_USER: postgres
      TSTUNE_PROFILE: promscale

  grafana:
    container_name: grafana
    image: grafana/grafana:9.3.2
    restart: on-failure
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    networks:
      - grafana
      - timescaledb
    depends_on:
      - timescaledb
    ports:
      # WSL2 binds port :3000
      - "3001:3000/tcp"
    volumes:
      - grafana-data:/etc/grafana/provisioning/

volumes:
  timescaledb-data:
  grafana-data:
